.PHONY: process1 process2 process3 process4

all: process1 process2 process3 process4

process1:
	g++ process1.cpp -o process1

process2:
	g++ process2.cpp -o process2

process3:
	g++ process3.cpp -o process3

process4:
	g++ -g3 process4.cpp -o process4